import java.sql.*;
import java.text.SimpleDateFormat;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ELCOT
 */
public class ladies extends javax.swing.JFrame {

    /**
     * Creates new form ladies
     */
    public ladies() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        size1 = new javax.swing.JComboBox<>();
        saree = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        size2 = new javax.swing.JComboBox<>();
        chudidar = new javax.swing.JTextField();
        total1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        total = new javax.swing.JTextArea();
        back = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        print = new javax.swing.JButton();
        payment = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        size3 = new javax.swing.JComboBox<>();
        tops = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 204, 204));
        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jLabel1.setText("SAREE");

        size1.setBackground(new java.awt.Color(255, 204, 204));
        size1.setFont(new java.awt.Font("Viner Hand ITC", 3, 14)); // NOI18N
        size1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COTTON", "SILK", "FANCY", "POONAM", "KANJIPATTU", "PATTU", "CHINAPATTU" }));

        jLabel2.setBackground(new java.awt.Color(255, 204, 204));
        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jLabel2.setText("CHUDIDAR");

        size2.setBackground(new java.awt.Color(255, 204, 204));
        size2.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        size2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));

        chudidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chudidarActionPerformed(evt);
            }
        });

        total1.setBackground(new java.awt.Color(255, 204, 204));
        total1.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        total1.setText("TOTAL");
        total1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total1ActionPerformed(evt);
            }
        });

        total.setColumns(20);
        total.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 14)); // NOI18N
        total.setRows(5);
        jScrollPane1.setViewportView(total);

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 204, 204));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(255, 204, 204));
        clear.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        print.setBackground(new java.awt.Color(0, 0, 0));
        print.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        print.setForeground(new java.awt.Color(255, 204, 204));
        print.setText("PRINT");
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        payment.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 18)); // NOI18N

        jTextField1.setBackground(new java.awt.Color(255, 204, 204));
        jTextField1.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        jTextField1.setText("TOPS");

        size3.setBackground(new java.awt.Color(255, 204, 204));
        size3.setFont(new java.awt.Font("Viner Hand ITC", 3, 18)); // NOI18N
        size3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "S", "M", "L" }));
        size3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                size3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(38, 38, 38)
                                            .addComponent(size1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(19, 19, 19)
                                            .addComponent(size3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(chudidar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(saree, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                        .addComponent(tops)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(clear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(total1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(size2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(back)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(print)
                        .addGap(14, 14, 14))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(size1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chudidar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(size2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tops, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total1)
                    .addComponent(clear))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(print)
                    .addComponent(back))
                .addGap(15, 15, 15))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(payment, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int num1;
int num2;
int num3;
double amount1;
double amount2;
double amount3;
double tot;
double tot2;
double gst;
    private void total1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total1ActionPerformed
        num1=Integer.parseInt(saree.getText());
        if(size1.getSelectedItem().toString()=="COTTON")
         amount1=   num1*1000;
        else if(size1.getSelectedItem().toString()=="SILK")
         amount1=   num1*1500;
         else if(size1.getSelectedItem().toString()=="FANCY")
         amount1=   num1*1800;
        else if(size1.getSelectedItem().toString()=="POONAM")
         amount1=   num1*1600;
        else if(size1.getSelectedItem().toString()=="KANJIPATTU")
         amount1=   num1*1850;
        else if(size1.getSelectedItem().toString()=="PATTU")
         amount1=   num1*1700;
         else
            amount1=num1*2000;
            
          
          
            
          
         
            
          
          
                    
        
        num2=Integer.parseInt(chudidar.getText()); 
         if(size2.getSelectedItem().toString()=="S")
             amount2=num2*800;
        else if(size2.getSelectedItem().toString()=="M")
              amount2=num2*1000;
         else
            amount2=num2*1500;
         
         num3=Integer.parseInt(tops.getText()); 
         if(size2.getSelectedItem().toString()=="S")
             amount3=num2*600;
        else if(size2.getSelectedItem().toString()=="M")
              amount3=num2*900;
         else
            amount3=num2*1300;
         
         tot=amount1+amount2+amount3;
         if(tot>=1000)
             gst=(tot*12)/100;
         else
             gst=(tot*5)/100;
         tot2=tot+gst;
       payment.setText(payment.getText()+tot2);  
         
       String s=saree.getText();
         String c=chudidar.getText();
         String m=tops.getText();
         String t=payment.getText();
         
         
         PreparedStatement ps;
     String query="INSERT INTO `ladies`(`saree`,`chudidar`,`tops`,`payment`)VALUES(?,?,?,?)";
     try{
         ps=Myconnection.getConnection().prepareStatement(query);
         
         ps.setString(1,s);
         ps.setString(2,c);
         ps.setString(3,m);
         ps.setString(4,t);
         if(ps.executeUpdate()>0)
         {
             JOptionPane.showMessageDialog(null, "thankyou");
         }
     }catch(Exception ex){
         System.out.println(ex);
     }
         total.setText(total.getText() +"\n");
          total.setText(total.getText()+"\t"+"=============" +"\n");
           total.setText(total.getText()+"\t" +"VK READYMADES" +"\n"+"\t"+"THANJAVUR"+"\n"+"\t"+"PH-1122334455"+"\n");
            total.setText(total.getText()+"\t"+"============="  +"\n");
           total.setText(total.getText() +"\n"); 
          total.setText(total.getText() +"saree ="  +amount1 +"\n");
           total.setText(total.getText() +"\n");
           total.setText(total.getText() +"chudidar ="  +amount2+"\n");
            total.setText(total.getText() +"\n");
            total.setText(total.getText()+"tops=" +amount3+"\n");
             total.setText(total.getText() +"\n");
           total.setText(total.getText() +"gst ="  +gst +"\n");
            total.setText(total.getText() +"\n");
            total.setText(total.getText() +"total ="  +tot2+"\n");
             total.setText(total.getText() +"\n");
             total.setText(total.getText() +     "THANKYOU COMEAGIN");
             
            
        
        
        
    }//GEN-LAST:event_total1ActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
       entrance e=new entrance();
        e.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
      total.setText("");
      num1=(0);
      num2=(0);
      amount1=(0);
      amount2=(0);
      gst=(0);
      tot2=(0);
    }//GEN-LAST:event_clearActionPerformed

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        try {
            total.print();
        } catch (PrinterException ex) {
            Logger.getLogger(ladies.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printActionPerformed

    private void chudidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chudidarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chudidarActionPerformed

    private void size3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_size3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_size3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ladies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ladies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ladies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ladies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ladies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JTextField chudidar;
    private javax.swing.JButton clear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField payment;
    private javax.swing.JButton print;
    private javax.swing.JTextField saree;
    private javax.swing.JComboBox<String> size1;
    private javax.swing.JComboBox<String> size2;
    private javax.swing.JComboBox<String> size3;
    private javax.swing.JTextField tops;
    private javax.swing.JTextArea total;
    private javax.swing.JButton total1;
    // End of variables declaration//GEN-END:variables
}
